name: Auto-Clean

on:
  workflow_dispatch:
    inputs:
      NUMBER0:
        description: "releases keep latest"
        default: '20'
        required: false
        type: string

      NUMBER1:
        description: "workflows keep day"
        default: '14'
        required: false
        type: string

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: ${{inputs.NUMBER0 || '0'}}
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: ${{inputs.NUMBER1 || '0'}}
